---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-gatekeeper
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Dakshayani2005/multi-cluster-platform.git
    targetRevision: main
    path: gitops-repo/platform/gatekeeper
  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
